version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cars-frontend
    ports:
      - "3001:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    restart: unless-stopped
    networks:
      - cars-network

networks:
  cars-network:
    external: true